Task17 heroku
Lichers0/Module2 pull request #19
Opened 2020-10-28 10:19 UTC by Lichers0

2020-10-28 15:54 UTC, VidgarVii requested changes

2020-10-28 15:54 UTC, VidgarVii commented on app/controllers/feedback_controller.rb
> +    FeedbackMailer.send_feedback(current_user.id, params[:title], params[:body]).deliver_now!
для мейлера deliver_now более чем достаточно для прода.

2020-10-28 15:54 UTC, VidgarVii commented on app/javascript/utilities/form_inline.js
>  }
вконце файла надо пустые строчки оставлять) это указатель на конец файла

2020-10-28 15:54 UTC, VidgarVii commented on app/mailers/application_mailer.rb
> +  default from: %{"Test Guru" <noreply@testguru.com>}
на будущие такие вещи хорошо где-нить в настройках хранить. Очень популярный гем config

2020-10-28 15:54 UTC, VidgarVii commented on app/mailers/feedback_mailer.rb
> +    @user = User.find(user_id)
1 [Тут](https://github.com/Lichers0/Module2/pull/19/files#diff-e467c5b47bb2e7c8fdc2dc716534885674a9f87bacc28694058361f31ed19e23R5) ты уже обращаешься к существующему объекту юзер. 
2 Вытаскиваешь у него ид
3 ИД юзера отдаешь в мэйлер
4 Тут по ид лезешь в базу для получения объекта юзер

что-то тут не то... да?))

2020-10-28 15:54 UTC, VidgarVii commented on app/servises/gist_question_service.rb
> +    @result&.html_url.present?
не очень хорошо когда предикат может вернуть нил

2020-10-28 15:54 UTC, VidgarVii commented on app/servises/gist_question_service.rb
> +    @result.html_url
а этот публичный метод всегда содержит @result? метод #success? говорит нет.

Надо что-то с логикой сделать.

2020-10-28 15:54 UTC, VidgarVii commented on app/views/admin/tests/_form_inline.html.erb
>               url: update_inline_admin_test_path(test),
по легче) где красивые отступы в 2 пробела?)

2020-10-28 15:54 UTC, VidgarVii commented on app/views/feedback/new.html.erb
> +<% end %>
нет пустой строки. надо с этим что-то делать)

2020-10-28 15:54 UTC, VidgarVii commented on config/database.yml
> +  password: p12345
это тут точно лишние. В репозитории такие данные не должны лежать. Сам файл database.yml следует положить в гитигнор. И создать database.example.yml

2020-10-28 15:54 UTC, VidgarVii commented on config/environments/development.rb
> +  config.action_mailer.delivery_method = :smtp
letter_opener ?

2020-10-28 17:16 UTC, max-underthesun reviewed
пользовательскую часть приложения посмотреть не удалось:
при попытке регистрации приложение упало с 500-ой ошибкой (причем в базе пользователь сохранился, потому что повторная попытка зарегистрировать тот же email вернула ошибку о сущестовании пользователя), письмо для подтверждения регистрации не пришло

админка:
- когда логинился в консоли броузера выпала ошибка: `Uncaught TypeError: Cannot read property 'value' of null...` 
- попытка отправки обратной свзяи закончилась 500-ой ошибкой
- при сохранении формы для теста с невалидными данными (пустой тайтл) в консоли броузера ошибка `Uncaught TypeError: Cannot read property 'classList' of null ...`
- создать новый тест не удалось: выбранная в селекте категория сбрасывается, форма выводит ошибку "Category не может отсутствовать"
- если попробовать редактировать имя теста "инлайн" и попытаться сохранить пустое поле -форма возвращает ошибку, что верно, далее если нажать на "Отмена", а потом снова на "Редактировать" поле откроется пустым, что не очень верно (при открытии формы в поле должно быть текущее значение для тайтла)
- вообще не очень верно, что из админки можно "проходить тесты", по хорошему только администрирование должно быть доступно, а прохождение только из пользовательской сессии
- по завершению прохождения теста снова 500-я

2020-10-28 17:16 UTC, max-underthesun commented on app/controllers/feedback_controller.rb
> +class FeedbackController < ApplicationController
вряд ли в этом контроллере нужна аутентификация (она наследуется от `ApplicationController`)
думаю отправить сообщение может и не залогиненный пользователь
проблемы могут возникнуть и с логином, о чем пользователь захочет сообщить админу
кстати ссылка на форму обратной связи у тебя доступна со страницы логина, но переход по ней запрещен из-за аутентификации

2020-10-28 17:16 UTC, max-underthesun commented on app/controllers/feedback_controller.rb
> +class FeedbackController < ApplicationController
а в форму нужно добавить поле `email`, которого там сейчас нет, чтобы незалогиненный пользователь мог оставить свой адрес (и соответсвенно поправить контроллер под работу с незалогиненным пользователем)

2020-10-28 17:16 UTC, max-underthesun commented on app/mailers/feedback_mailer.rb
> +    mail to: admin_list, subject: t(".subject")
здесь адресат по сути используется дефолтный (он не задается динамически от письма к письму в зависимости от пришедших аргументов)

дефолтных адресатов более правильно устанавливать на уровне класса, как это описано [в документации](https://guides.rubyonrails.org/action_mailer_basics.html#sending-email-to-multiple-recipients)

2020-10-28 17:16 UTC, max-underthesun commented on app/controllers/feedback_controller.rb
> +    FeedbackMailer.send_feedback(current_user.id, params[:title], params[:body]).deliver_now!
прежде чем слать письмо, нужно проверить что пользователь передал валидные данные - логично, что `email` и `body` не должны быть пустыми, может быть стоит проверить `email` на то что он соответсвует формату электроннго адреса

2020-10-29 12:34 UTC, Lichers0 commented on app/views/admin/tests/_form_inline.html.erb
>               url: update_inline_admin_test_path(test),
Данный вид отступа, так же является хорошим в ruby-style-guide
Фрагмент гайда закоментил в файле

2020-10-29 12:42 UTC, Lichers0 commented on config/environments/development.rb
> +  config.action_mailer.delivery_method = :smtp
Данным гемом и пользовался на этапе разработки, но при деплои на хероку пошли проблемы с отсылкой писем(в логах просто пишет что 500 ошибка и все).
Пришлось проверять работу отсылки gmail локально. Если нужно будет верну обратно но пока (как я понял проблема осталась)...

2020-10-31 11:10 UTC, VidgarVii requested changes

2020-10-31 11:10 UTC, VidgarVii commented on app/controllers/feedback_controller.rb
> +    else
ни какой бизнес логики и формирования представлений не должно быть в контроллерах. Контроллер это всего лишь делегатор задач. 
Тут у тебя должно остаться
```
@feedback = Feedback.new(feedback_params)

if @feedback.valid?
  FeedbacksMailer.send_message(@feedback).deliver_now
  redirect_to ..
else
  render :new
end
```
А еще лучше всю логику утощить в сервис. Чтобы он же проверял валидацию и он же отвечал за отправку почты

2020-10-31 11:10 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    result = service.call
я бы создал еще один сервис, типо GistCreator, где была бы инкапсулирована логика создания самого гиста и запись гиста в БД, если это требуется. А в контроллере я бы просто проверял success или нет. А полученную инфу отдавал бы в представление.

2020-10-31 11:10 UTC, VidgarVii commented on app/controllers/users/registrations_controller.rb
> +    # super(resource)
лишние коменты можно удалить, чтобы не появлялись вопросы

2020-10-31 11:10 UTC, VidgarVii commented on app/models/feedback.rb
> +end
нет пустой строки

2020-10-31 11:10 UTC, VidgarVii commented on app/views/admin/tests/_form_inline.html.erb
> +  # # хорошо
оставлять такое не хорошо

2020-10-31 11:10 UTC, VidgarVii commented on config/environments/production.rb
> +    address:            'tisza.hostven02.ru',
для прода удобно будет все подобные настройки выводить в env переменные. Так не придется каждый раз пушить в гит изменения

2020-11-02 05:47 UTC, merged